export default {
    intro_Image: require('../assets/images/ic_1.png'),
    logo_Image: require('../assets/images/logo.png'),
    google_Logo: require('../assets/images/ic_google.png'),
    facebook_Logo: require('../assets/images/ic_facebook.png'),
    apple_Logo: require('../assets/images/ic_apple.png'),
    back_Arrow: require('../assets/images/ic_back_arrow.png'),
    drop_Down: require('../assets/images/ic_down.png'),
    home: require('../assets/images/ic_home.png'),
    search : require('../assets/images/ic_srch.png'),
    add_Post: require('../assets/images/ic_add.png'),
    notification: require('../assets/images/ic_notify.png'),
    profile: require('../assets/images/ic_user.png'),
    setting: require('../assets/images/ic_dots.png'),
    direction: require('../assets/images/ic_direction.png'),
    home_Icon: require('../assets/images/ic_home_icon.png'),
    location: require('../assets/images/ic_loc.png'),
    user_Profile: require('../assets/images/ic_usrr_1.png'),
    change_Password: require('../assets/images/ic_key.png'),
    signout: require('../assets/images/ic_logout.png'),
    profile_Image1: require('../assets/images/postIamge.jpeg'),
    post_Image1: require('../assets/images/PostIMAGES.jpeg'),
    profile_Image2: require('../assets/images/Pro.jpeg'),
    edit_image: require('../assets/images/ic_edit.png'),
    post_Image2: require('../assets/images/pexels-photo-2715004.jpeg'),
    cross: require('../assets/images/ic_cross.png'),
    camera: require('../assets/images/photo-camera-interface-symbol-for-button.png')
};