export default {
    INTRO_IMAGE: require('../assets/images/ic_1.png'),
    LOGO_IMG: require('../assets/images/logo.png'),
    GOOGLE_LOGO: require('../assets/images/ic_google.png'),
    FACEBOOK_LOGO: require('../assets/images/ic_facebook.png'),
    APPLE_LOGO: require('../assets/images/ic_apple.png'),
    BACK_ARROW: require('../assets/images/ic_back_arrow.png'),
    DROP_DOWN: require('../assets/images/ic_down.png'),
    HOME: require('../assets/images/ic_home.png'),
    SEARCH : require('../assets/images/ic_srch.png'),
    ADD_POST: require('../assets/images/ic_add.png'),
    NOTIFICATION: require('../assets/images/ic_notify.png'),
    PROFILE: require('../assets/images/ic_user.png'),
    SETTING: require('../assets/images/ic_dots.png'),
    DIRECTION: require('../assets/images/ic_direction.png'),
    HOME_ICON: require('../assets/images/ic_home_icon.png'),
    LOCATION: require('../assets/images/ic_loc.png'),
    USER_PROFILE: require('../assets/images/ic_usrr_1.png'),
    CHANGE_PASSWORD: require('../assets/images/ic_key.png'),
    SIGNOUT: require('../assets/images/ic_logout.png'),
    PROFILE_IMAGE1: require('../assets/images/postIamge.jpeg'),
    POST_IMAGE1: require('../assets/images/PostIMAGES.jpeg'),
    PROFILE_IMAGE2: require('../assets/images/Pro.jpeg'),
    EDIT_IMAGE: require('../assets/images/ic_edit.png')
};