export {default as Search} from './Search/Search'
export {default as Home} from './Home/Home'
export {default as Notification} from './Notification/Notification'
export {default as AddInfo} from './AddInfo/AddInfo'
export {default as ChangePassword} from './ChangePassword/ChangePassword'
export {default as EditProfile } from './EditProfile/EditProfile'
// export {default as Location} from './Location/Location'
export {default as Location} from  './Location/Location'
export {default as Post} from './Post/Post'
export {default as PostDetails } from './PostDetails/PostDetails'
export {default as Profile} from './Profile/Profile'
export {default as Comments} from './Comments/Comments'